default:
    @just --list

files := """
    syllabus.typ
    overview.typ
    jaccard.typ
    hw1.typ
    hw1-ru.typ
    hw2.typ
    lec-set-theory.typ
    lec-relations.typ
    lec-boolean-algebra.typ
    lec-logic.typ
    lec-flow.typ
    lec-formal.typ
    lec-nfa.typ
    lec-regular.typ
    lec-combinatorics.typ
    test1.typ
    test2.typ
    test3.typ
    test4.typ
"""

all:
    #!/usr/bin/env sh
    set -e
    for file in {{replace(files, "\n", ' ')}}; do
        if [ -f $file ]; then
            just compile $file
        else
            echo "File '$file' does not exist!"
        fi
    done

compile target:
    typst compile {{target}}

parallel:
    parallel -k -- just compile {} ::: {{replace(files, "\n", ' ')}}
