default:
    @just --list

all: \
    (compile "lec-set-theory.typ") \
    (compile "lec-boolean-algebra.typ") \
    (compile "lec-logic.typ") \
    (compile "lec-flow.typ") \
    (compile "lec-formal.typ") \
    (compile "lec-nfa.typ") \
    (compile "lec-regular.typ") \
    (compile "lec-combinatorics.typ")

compile target:
    typst compile {{target}}
