default:
    @just --list

files := """
    syllabus.typ
    overview.typ
    hw1.typ
    hw1-ru.typ
    hw2.typ
    lec-set-theory.typ
    lec-relations.typ
    lec-boolean-algebra.typ
    lec-logic.typ
    lec-flow.typ
    lec-formal.typ
    lec-nfa.typ
    lec-regular.typ
    lec-combinatorics.typ
"""

all:
    #!/usr/bin/env sh
    for file in {{replace(files, "\n", ' ')}}; do
        just compile $file || exit 0
    done

compile target:
    typst compile {{target}}

parallel:
    parallel -k -- just compile {} ::: {{replace(files, "\n", ' ')}}
