#import "theme.typ": *
#show: slides.with(
  title: [Discrete Mathematics],
  subtitle: "Generating Functions",
  date: "Spring 2025",
  authors: "Konstantin Chukharev",
  ratio: 16 / 9,
  // dark: true,
)

#show table.cell.where(y: 0): strong

// Style the quote block
#set quote(block: true)
#show quote: set par(justify: false)
#show quote: set align(left)

#let power(x) = $cal(P)(#x)$
#let stirling(n, k) = $vec(delim: "{", #n, #k)$
#let s2(n, k) = $s^("II")_(#k) (#n)$

= Generating Functions

== Generating Functions

#block(width: 90%)[
  #quote(attribution: [George Pólya, Mathematics and Plausible Reasoning @polya1954])[
    _A generating function is a device somewhat similar to a bag. Instead of carrying many little objects detachedly, which could be embarrassing, we put them all in a bag, and then we have only one object to carry, the bag._
  ]
]

#quote(attribution: [Herbert Wilf, generatingfunctionology @wilf2006])[
  _A generating function is a clothesline on which we hang up a sequence of numbers for display._
]

#place(bottom + center)[
  #grid(
    columns: 3,
    align: top + center,
    column-gutter: 1em,
    row-gutter: 0.5em,
    image("assets/Abraham_de_Moivre.jpg", height: 3cm),
    image("assets/George_Polya.jpg", height: 3cm),
    image("assets/Herbert_Wilf.jpg", height: 3cm),

    [Abraham \ de Moivre], [George Pólya], [Herbert Wilf],
  )
]

== Ordinary Generating Functions

#definition[
  An _ordinary generating function_ (OGF) of a sequence $a_n$ is a _power series_
  $
    G(a_n; x) = sum_(n = 0)^(infinity) a_n x^n
  $
]

#example[
  The _sequence_ $a_n = (a_0, a_1, a_2, dots)$ is _generated_ by the OGF $G(x) = a_0 + a_1 x + a_2 x^2 + dots$
]

#example[
  $G(x) = 3 + 8x^2 + x^3 + 1 / 7 x^5 + 100 x^6 + ...$ _generates_ the sequence $(3, 8, 1, 1 / 7, 100, dots)$
]

#example[
  Consider a long division of $1$ by $(1 - x)$, the result is an infinite power series
  $
    frac(1, 1 - x) = 1 + x^1 + x^2 + x^3 + dots = sum_(n = 0)^(infinity) x^n
  $
  Note that all coefficients are $1$.
  Thus, the generating function of $(1, 1, 1, dots)$ is $G(x) = sum_(n = 0)^(infinity) x^n = frac(1, 1 - x)$.
]

== More Examples of Generating Functions

Another proof that $(1, 1, 1, dots)$ is generated by $G(x) = 1 + x + x^2 + x^3 + dots = sum_(n = 0)^(infinity) x^n = frac(1, 1 - x) = S$:
#grid(
  columns: 3,
  inset: (2pt, 5pt),
  align: (right + horizon, center + horizon, left + horizon),
  stroke: (x, y) => if y == 1 { (bottom: .6pt) },
  $S$, $=$, $1 + x + x^2 + x^3 + dots$,
  $x dot S$, $=$, $#hide($0 +$) x + x^2 + x^3 + dots$,
  $S - x dot S$, $=$, $1$,
)
Thus, $display(S = 1 / (1 - x))$

#pagebreak()

$
  & 1 / (1 - x) = sum_(n = 0)^(infinity) x^n = 1 + x + x^2 + x^3 + dots & "generates" & (1, 1, 1, dots) & "(constant "1")" \
  & 2 / (1 - x) = sum_(n = 0)^(infinity) 2 x^n = 2 + 2x + 2x^2 + 2x^3 + dots & "generates" & (2, 2, 2, dots) & "(constant "2")" \
  & x / (1 - x) = sum_(n = 1)^(infinity) x^n = x + x^2 + x^3 + dots & "generates" & (0, 1, 1, 1, dots) & "(right shift)" \
  & 1 / (1 + x) = sum_(n = 0)^(infinity) (-1)^n x^n = 0+ 1 - x + x^2 - x^3 + dots & "generates" & (1, -1, 1, dots) & "(sign-alternating "1"'s)" \
  & 1 / (1 - 3x) = sum_(n = 0)^(infinity) 3^n x^n = 1 + 3x + 9x^2 + 27x^3 + dots & "generates" & (1, 3, 9, dots) & "(powers of "3")" \
  & 1 / (1 - x^2) = sum_(n = 0)^(infinity) x^n = 1 + x^2 + x^4 + x^6 + dots & "generates" & (1, 0, 1, 0, dots) & "(regular gaps)" \
  & 1 / (1 - x)^2 = sum_(n = 0)^(infinity) (n+1) x^n = 0 + x + 2x^2 + 3x^3 + dots & "generates" & (1, 0, 1, 0, dots) & "(natural numbers)" \
$

#pagebreak()

$
  frac(1-x^(n+1), 1-x)
  &= frac(1, 1-x) - frac(x^(n+1), 1-x) = \
  &eq.delta (1,1,1,dots) - \(underbrace(0\,0\,dots\,0, n+1 "zeros"),1,1,dots) = \
  &= \(underbrace(1\,1\,dots\,1, n+1 "ones"), 0,0,dots) = \
  &eq.delta 1 + x + x^2 + dots + x^n
$

== Exercises

#example[
  Find GF for odd numbers: $(1, 3, 5, dots)$.

  //      A(x) = 1 + 3x + 5x^2 + 7x^3 + 9x^4 + ...
  //  x * A(x) = 0 + 1x + 3x^2 + 5x^3 + 7x^4 + ...
  // ----------------------------------------------
  //   (1-x)*A = 1 + 2x + 2x^2 + 2x^3 + 2x^4 + ...
  //   (1-x)*A = 1 + 2x/(1-x)
  //
  // A(x) = 1/(1-x) + 2x/(1-x)^2  ===  (1+x) / (1-x)^2 =
  //  = (1,1,1,...) + (0,2,4,6,8,...) = (1,3,5,7,9,...)
]

#example[
  Find GF for $(1, 3, 7, 15, 31, 63)$, which satisfies $a_n = 3 a_(n-1) - 2 a_(n-2)$ with $a_0 = 1$, $a_1 = 3$.

  //      A = 1 + 3x + 7x^2 + 15x^3 + 31x^4 + ... + a_n x^n + ...
  //   -3xA = 0 - 3x - 9x^2 - 21x^3 - 45x^4 - ... - 3a_(n-1) x^n - ...
  //  2x^2A = 0 + 0x + 2x^2 +  6x^3 + 18x^4 + ... + 2a_(n-2) x^n + ...
  // ------------------------------------------------------------------
  // (1 - 3x + 2x^2) A = 1
  //
  // Thus, A(x) = 1 / (1 - 3x + 2x^2)

  // Note: rewrite (a_n) as a_n - 3a(n-1) + 2a(n-2) = 0
  // observe the similarity to A(x)
]

== Solving Combinatorial Problems via Generating Functions

#example[
  Find the number of integer solutions to $x_1 + x_2 + x_3 = 12$ with $0 <= x_i <= 6$.

  - Possible values for $x_1$: $0, 1, dots, 6$.
  - Write this as a polynomial $x^0 + x^1 + dots + x^6$.
  - Do the same for $x_2$ and $x_3$.
  - Since all combinations of $x_1$, $x_2$ and $x_3$ are suitable non-conflicting solutions, we can multiply those polynomials and obtain the _generating function_ $G(x) = (1 + x + x^2 + dots + x^6)^3$.
  - For each $n$, the coefficient of $x^n$ in $G(x)$ is the number of integer solutions to $x_1 + x_2 + x_3 = n$.
  - Specifically, we are interested in the coefficient of $x^12$ in $G(x)$, denoted $[x^12] G(x)$.
  - Use #strike[pen and paper] #link("https://www.wolframalpha.com/input?i=expand+%281%2Bx%2Bx%5E2%2Bx%5E3%2Bx%5E4%2Bx%5E5%2Bx%5E6%29%5E3")[Wolfram Alpha] to expand $G(x)$:
    $
      G(x) = x^18 + 3x^17 + 6x^16 + dots + underparen(28x^12) + dots + 6x^2 + 3x + 1
    $
  - The answer is $[x^12] G(x) = 28$ solutions.
]

== Slightly More Complex Combinatorial Problem

#example[
  Suppose we have marbles of three different colors (#emoji.circle.red, #emoji.circle.green, #emoji.circle.blue), and we want to _count_ the number of ways to select 20 marbles, such that:
  - There are an even number of #emoji.circle.red: $1 + x^2 + x^4 + dots + x^20$.
  - There are at least 12 #emoji.circle.green: $x^12 + x^13 + dots + x^20$.
  - There are at most 5 #emoji.circle.blue: $1 + x + x^2 + x^3 + x^4 + x^5$.

  Multiply polynomials and find $[x^20] G(x)$:
  $
    & [x^20] (1+x^2+x^4+dots+x^20) (x^12+x^13+dots+x^20) (1+x+x^2+x^3+x^4+x^5) = \
    & = [x^20] (x^45 + 2x^44 + dots + 21x^20 + dots + 2x^13 + x^12) \
    & = 21
  $
]

== Using Power Series in Combinatorial Problems

#example[
  Find the number of integer solutions to $x_1 + x_2 + x_3 = 12$ with $x_1 >= 2$, $3 <= x_2 <= 6$, $x_3 <= 9$.

  - Compose the generating function:
    $
      G(x) = (x^2 + x^3 + dots) dot (x^3 + x^4 + x^5 + x^6) dot (1 + x + x^2 + dots + x^9)
    $

  - Substitute the power series with the corresponding simple forms:
    $
      G(x) = (x^2 dot frac(1, 1-x)) dot (x^3 dot frac(1-x^4, 1-x)) dot (frac(1-x^10, 1-x))
    $
]

== Bibliography
#bibliography("refs.yml")
