// Diagrams for the Kripke chapter (m32): traffic-light Kripke structure
// and the modal cube of normal modal systems.
#import "../requirements.typ": *
#import "../notation.typ": *

#import cetz: canvas, draw
#import fletcher: diagram, edge, node

#let k-node = oklch(88%, 0.03, 250deg)
#let k-node-str = oklch(60%, 0.08, 250deg)
#let k-edge = oklch(35%, 0.02, 265deg) + 0.6pt
#let k-label = oklch(35%, 0.02, 265deg)
#let k-forbidden = (paint: oklch(55%, 0.19, 25deg), thickness: 0.8pt, dash: "dashed")

// Traffic light: states G (green), Y (yellow), R (red) on a 3-cycle.
#let kripke-traffic = canvas({
  let r = 0.45
  draw.circle((0, 0.9), radius: r, fill: k-node, stroke: k-node-str, name: "G")
  draw.content((0, 0.9), text(size: 0.72em, fill: k-label)[$G$])

  draw.circle((0.95, -0.55), radius: r, fill: k-node, stroke: k-node-str, name: "Y")
  draw.content((0.95, -0.55), text(size: 0.72em, fill: k-label)[$Y$])

  draw.circle((-0.95, -0.55), radius: r, fill: k-node, stroke: k-node-str, name: "R")
  draw.content((-0.95, -0.55), text(size: 0.72em, fill: k-label)[$R$])

  draw.line("G", "Y", stroke: k-edge, mark: (end: ">"))
  draw.line("Y", "R", stroke: k-edge, mark: (end: ">"))
  draw.line("R", "G", stroke: k-edge, mark: (end: ">"))

  // Atom labels: which atomic proposition is true in each state.
  draw.content((0, 1.5), anchor: "south", text(size: 0.62em, fill: k-label)[${"green"}$])
  draw.content((1.05, -1.15), anchor: "west", text(size: 0.62em, fill: k-label)[${"yellow"}$])
  draw.content((-1.05, -1.15), anchor: "east", text(size: 0.62em, fill: k-label)[${"red"}$])
})

// ── Modal cube: systems generated by axioms T, B, 4 over K ──
// Axes: T (right), B (up), 4 (diagonal). Each vertex = K + a subset of
// {T, B, 4}; an edge = adding one axiom. D sits on the K→T edge
// (D ⊂ T, but D is not an axis of the cube).
#let mc-n-size = 1.4em
#let mc-n-fill = oklch(88%, 0.03, 250deg)
#let mc-n-str = 0.6pt + oklch(60%, 0.08, 250deg)
#let mc-dim-fill = oklch(94%, 0.008, 265deg)
#let mc-dim-str = 0.6pt + oklch(55%, 0.02, 265deg)
#let mc-dim-label = oklch(50%, 0.02, 265deg)
#let mc-e-str = 0.6pt + oklch(35%, 0.02, 265deg)
#let mc-label = oklch(35%, 0.02, 265deg)
#let mc-d-fill = oklch(93%, 0.06, 65deg)
#let mc-d-str = 0.8pt + oklch(60%, 0.12, 65deg)

// Modal cube drawn as two squares (T × B plane, shifted by the 4 axis).
#let modal-cube = canvas({
  let r = 0.36
  // Single source of truth for positions: edges and nodes share these.
  let pk = (0, 0)
  let pt = (1.7, 0)
  let pkb = (0, 1.7)
  let pb = (1.7, 1.7)
  let pk4 = (0.6, 1.0)
  let ps4 = (2.3, 1.0)
  let pkb4 = (0.6, 2.7)
  let ps5 = (2.3, 2.7)
  let pd = (0.55, 0)

  let wnode(pos, body, name, fill: mc-n-fill, stroke: mc-n-str, label: mc-label) = {
    draw.circle(pos, radius: r, fill: fill, stroke: stroke, name: name)
    draw.content(pos, text(size: 0.6em, fill: label)[#body])
  }
  let wedge(a, b) = draw.line(a, b, stroke: mc-e-str)

  // Cube frame: bottom square (T × B), top square (+4), verticals.
  wedge(pk, pt)
  wedge(pk, pkb)
  wedge(pt, pb)
  wedge(pkb, pb)
  wedge(pk4, ps4)
  wedge(pk4, pkb4)
  wedge(ps4, ps5)
  wedge(pkb4, ps5)
  wedge(pk, pk4)
  wedge(pt, ps4)
  wedge(pkb, pkb4)
  wedge(pb, ps5)

  // Axis labels: adding one axiom.
  draw.content((0.85, -0.42), text(size: 0.55em, fill: mc-dim-label)[+$T$])
  draw.content((-0.5, 0.85), text(size: 0.55em, fill: mc-dim-label)[+$B$])
  draw.content((0.18, 0.62), text(size: 0.55em, fill: mc-dim-label)[+$4$])

  // Bottom square: K, T, KB, B.
  wnode(pk, $K$, "k")
  wnode(pt, $T$, "t")
  wnode(pkb, $K B$, "kb", fill: mc-dim-fill, stroke: mc-dim-str, label: mc-dim-label)
  wnode(pb, $B$, "b")

  // Top square: K4, S4, KB4, S5 (shifted along the 4 axis).
  wnode(pk4, $K_4$, "k4", fill: mc-dim-fill, stroke: mc-dim-str, label: mc-dim-label)
  wnode(ps4, $S_4$, "s4")
  wnode(pkb4, $K B_4$, "kb4", fill: mc-dim-fill, stroke: mc-dim-str, label: mc-dim-label)
  wnode(ps5, $S_5$, "s5")

  // D on the K→T edge: D ⊂ T, but D is not an axis of the cube.
  draw.circle(pd, radius: 0.24, fill: mc-d-fill, stroke: mc-d-str, name: "d")
  draw.content(pd, text(size: 0.55em, fill: mc-label)[$D$])
})

// ── Mutual exclusion: state space of two processes competing for a ──
// critical section. State (C,C) would violate crit_1 ∧ crit_2; the
// red dashed border marks it as forbidden (unreachable in a correct model).
#let mutex-states = canvas({
  let r = 0.42
  draw.circle((0, 0), radius: r, fill: k-node, stroke: k-node-str, name: "oo")
  draw.content((0, 0), text(size: 0.62em, fill: k-label)[${(O, O)}$])
  draw.content((0, -0.75), anchor: "north", text(size: 0.55em, fill: k-label)[$nothing$])

  draw.circle((-1.4, 1.4), radius: r, fill: k-node, stroke: k-node-str, name: "co")
  draw.content((-1.4, 1.4), text(size: 0.62em, fill: k-label)[${(C, O)}$])
  draw.content((-1.95, 1.4), anchor: "east", text(size: 0.55em, fill: k-label)[${"crit"_1}$])

  draw.circle((1.4, 1.4), radius: r, fill: k-node, stroke: k-node-str, name: "oc")
  draw.content((1.4, 1.4), text(size: 0.62em, fill: k-label)[${(O, C)}$])
  draw.content((1.95, 1.4), anchor: "west", text(size: 0.55em, fill: k-label)[${"crit"_2}$])

  draw.circle((0, 2.9), radius: r, fill: none, stroke: k-forbidden, name: "cc")
  draw.content((0, 2.9), text(size: 0.62em, fill: k-label)[${(C, C)}$])
  draw.content((0.55, 2.9), anchor: "west", text(size: 0.55em, fill: k-label)[${"crit"_1, "crit"_2}$])

  draw.line("oo", "co", stroke: k-edge, mark: (end: ">"))
  draw.line("oo", "oc", stroke: k-edge, mark: (end: ">"))
  draw.line("co", "oo", stroke: k-edge, mark: (end: ">"))
  draw.line("oc", "oo", stroke: k-edge, mark: (end: ">"))
})
