[private]
default:
    @just --list

files := """
    course-intro.typ
    s1-lec01-statements.typ
    s1-lec02-predicates.typ
    s1-lec03-sets.typ
    s1-lec04-relations.typ
    s1-lec05-equivalence.typ
    s1-lec06-order.typ
    s1-lec07-functions.typ
    s1-lec08-cardinality.typ
    s1-lec09-propositional.typ
    s1-lec10-deduction.typ
    s1-lec11-fol.typ
    s1-lec12-boolean-sat.typ
    s1-lec13-zhegalkin.typ
    s1-lec14-circuits.typ
    s1-lec15-codes.typ
    s1-lec16-compression.typ
    s2-lec01-graphs.typ
    s2-lec02-traversal.typ
    s2-lec03-matching.typ
    s2-lec04-planarity.typ
    s2-lec05-dfa.typ
    s2-lec06-nfa.typ
    s2-lec07-regex.typ
    s2-lec08-minimization.typ
    s2-lec09-turing.typ
    s2-lec10-universal.typ
    s2-lec11-halting.typ
    s2-lec12-decidability.typ
    s2-lec13-counting.typ
    s2-lec14-binomial.typ
    s2-lec15-genfun.typ
    s2-lec16-ramsey.typ
    lec-logic.typ
    lec-deduction.typ
    lec-fol.typ
    lec-sets.typ
    lec-relations.typ
    lec-functions.typ
    lec-cardinals.typ
    lec-orders.typ
    lec-graphs.typ
    lec-boolean.typ
    lec-circuits.typ
    lec-algebra.typ
    lec-codes.typ
    lec-sat.typ
    lec-smt.typ
    lec-logic-programming.typ
    lec-matroids.typ
    lec-combinatorics.typ
    lec-number-theory.typ
    lec-probability.typ
    lec-generating-fns.typ
    lec-constructions.typ
    lec-automata.typ
    lec-context-free.typ
    lec-turing.typ
    lec-decidability.typ
    lec-lambda.typ
    lec-type-theory.typ
    lec-modal.typ
    lec-intuitionism.typ
    lec-beyond-n.typ
    lec-complexity.typ
    lec-abstract-interpretation.typ
    lec-verification.typ
    lec-fuzzy.typ
    lec-category.typ
"""

# Compile all lectures
all:
    #!/usr/bin/env sh
    set -e
    for file in {{ replace(files, "\n", ' ') }}; do
        just _compile $file
    done

# Compile lectures in parallel
parallel:
    parallel -k -- just _compile {} ::: {{ replace(files, "\n", ' ') }}

# Compile one file
_compile *args:
    typst compile {{ args }}
