[workspace]
resolver = "2"
members = [
    "automata",
    "lambda",
    "crypto",
    "turing",
    "codes",
    "circuits",
    "sat",
    "smt",
    "model-checking",
    "heyting",
    "bdd",
    "analysis",
    "graphs",
    "prolog",
    "matroids",
    "lattices",
    "fitch",
    "fol",
    "algebra",
    "context-free",
    "combinatorics",
    "type-theory",
]
