[private]
default:
    @just --list

files := """
    course-intro.typ
    s1-mod1-sets.typ
    s1-mod2-relations.typ
    s1-mod3-logic.typ
    s1-mod4-boolean.typ
    s1-mod5-codes.typ
    lec-logic.typ
    lec-deduction.typ
    lec-fol.typ
    lec-sets.typ
    lec-relations.typ
    lec-functions.typ
    lec-cardinals.typ
    lec-orders.typ
    lec-graphs.typ
    lec-boolean.typ
    lec-circuits.typ
    lec-algebra.typ
    lec-codes.typ
    lec-sat.typ
    lec-smt.typ
    lec-logic-programming.typ
    lec-matroids.typ
    lec-combinatorics.typ
    lec-number-theory.typ
    lec-probability.typ
    lec-generating-fns.typ
    lec-constructions.typ
    lec-automata.typ
    lec-context-free.typ
    lec-turing.typ
    lec-decidability.typ
    lec-lambda.typ
    lec-type-theory.typ
    lec-modal.typ
    lec-intuitionism.typ
    lec-beyond-n.typ
    lec-complexity.typ
    lec-abstract-interpretation.typ
    lec-verification.typ
    lec-fuzzy.typ
"""

# Compile all lectures
all:
    #!/usr/bin/env sh
    set -e
    for file in {{ replace(files, "\n", ' ') }}; do
        just _compile $file
    done

# Compile lectures in parallel
parallel:
    parallel -k -- just _compile {} ::: {{ replace(files, "\n", ' ') }}

# Compile one file
_compile *args:
    typst compile {{ args }}
