//! Groups in action: residues mod 8, permutations, orders, powers, subgroups.

use algebra::traits::{Group, Semigroup};
use algebra::{order, power, subgroup, Perm, Unit, Zn};

fn main() {
    // Z_8 as an additive group.
    let one: Zn<8> = Zn::new(1);
    let two: Zn<8> = Zn::new(2);
    let three: Zn<8> = Zn::new(3);
    println!("1 + 3 = {:?} (mod 8)", one.op(&three));
    println!("inverse of 3 mod 8 = {:?}", three.inverse());

    // Orders: 1 has order 8 (it is a generator); 2 has order 4.
    println!("order of 1 in Z_8 = {:?} (a generator)", order(&one, 64));
    println!("order of 2 in Z_8 = {:?}", order(&two, 64));

    // Powers and the cyclic subgroup generated by 2.
    println!("3^5 in Z_8 = {:?}", power(&three, 5));
    let sub: Vec<u32> = subgroup(&two, 64).iter().map(|z| z.0).collect();
    println!("<2> in Z_8 = {:?}", sub);

    // S_3: a 3-cycle c = (0 1 2) -> (1 2 0).
    let c: Perm<3> = Perm([1, 2, 0]);
    let c2 = c.op(&c);
    let c3 = c2.op(&c);
    println!("c = {:?}", c);
    println!("c^2 = {:?}", c2);
    println!("c^3 = {:?} (back to identity)", c3);
    println!("order of c in S_3 = {:?}", order(&c, 64));

    // Units of Z_8: {1, 3, 5, 7} under multiplication, with inverses.
    let units: Vec<Unit<8>> = (1..8).filter_map(Unit::<8>::new).collect();
    println!(
        "units of Z_8: {:?}",
        units.iter().map(|u| u.0).collect::<Vec<_>>()
    );
    let u3 = Unit::<8>::new(3).unwrap();
    println!("inverse of 3 in Z_8^* = {:?}", u3.inverse().0);

    assert_eq!(order(&one, 64), Some(8));
    assert_eq!(order(&two, 64), Some(4));
    assert_eq!(order(&c, 64), Some(3));
    assert_eq!(sub, vec![0, 2, 4, 6]);
}
