//! Algebraic structures: semigroup, monoid, group, ring, field.
//!
//! A code companion to the algebra chapter. The structures are modeled as
//! Rust traits -- [`Semigroup`], [`Monoid`], [`Group`], [`Ring`], [`Field`] --
//! plus a few concrete instances. The bottom layer is deliberately built
//! from scratch: [`Nat`] is the Peano definition of the natural numbers, and
//! [`arithmetic`] hand-rolls the Euclidean algorithm that later yields
//! modular inverses. Above that layer the instances sit on the traits and
//! use standard iterators freely, showing how simple pieces assemble into
//! groups and rings.

pub mod arithmetic;
pub mod boolean;
pub mod nat;
pub mod perm;
pub mod traits;
pub mod zn;

pub use arithmetic::{extended_gcd, gcd, mod_inverse};
pub use boolean::Bool;
pub use nat::Nat;
pub use perm::Perm;
pub use traits::{Field, Group, Monoid, Ring, Semigroup};
pub use zn::{Unit, Zn};

/// `g^k` by repeated squaring: `O(log k)` applications of the operation.
///
/// Works for any monoid. The exponent is unsigned, so this stays on the
/// positive powers of a group.
pub fn power<M: Monoid>(g: &M, k: u64) -> M {
    let mut result = M::identity();
    let mut base = g.clone();
    let mut e = k;
    while e > 0 {
        if e % 2 == 1 {
            result = result.op(&base);
        }
        base = base.op(&base);
        e /= 2;
    }
    result
}

/// Smallest positive `k` with `g^k == identity`, or `None` if none is found
/// within `limit` steps. `limit` protects against infinite groups.
pub fn order<G: Group>(g: &G, limit: u64) -> Option<u64> {
    let mut cur = g.clone();
    for k in 1..=limit {
        if cur == G::identity() {
            return Some(k);
        }
        cur = cur.op(g);
    }
    None
}

/// The cyclic subgroup generated by `g`: `{identity, g, g^2, ...}` up to the
/// first return to the identity.
pub fn subgroup<G: Group>(g: &G, limit: u64) -> Vec<G> {
    let mut out = vec![G::identity()];
    let mut cur = g.clone();
    for _ in 1..limit {
        if cur == G::identity() {
            break;
        }
        out.push(cur.clone());
        cur = cur.op(g);
    }
    out
}

/// Whether a finite set of elements is abelian: `a op b == b op a` for all.
pub fn is_abelian<G: Group>(elements: &[G]) -> bool {
    for a in elements {
        for b in elements {
            if a.op(b) != b.op(a) {
                return false;
            }
        }
    }
    true
}
