compile := "typst compile --root ."

[private]
@default:
    just --list

book:
    {{ compile }} notes/book.typ

problems:
    {{ compile }} notes/problems.typ

lec-logic:
    {{ compile }} lectures/lec-logic.typ

lec-sets:
    {{ compile }} lectures/lec-sets.typ

lec-relations:
    {{ compile }} lectures/lec-relations.typ

lec-functions:
    {{ compile }} lectures/lec-functions.typ

lec-cardinals:
    {{ compile }} lectures/lec-cardinals.typ

lec-orders:
    {{ compile }} lectures/lec-orders.typ

lec-graphs:
    {{ compile }} lectures/lec-graphs.typ

lec-boolean:
    {{ compile }} lectures/lec-boolean.typ

lec-circuits:
    {{ compile }} lectures/lec-circuits.typ

lec-codes:
    {{ compile }} lectures/lec-codes.typ

lec-sat:
    {{ compile }} lectures/lec-sat.typ

lec-logic-programming:
    {{ compile }} lectures/lec-logic-programming.typ

lec-matroids:
    {{ compile }} lectures/lec-matroids.typ

lec-combinatorics:
    {{ compile }} lectures/lec-combinatorics.typ

lec-number-theory:
    {{ compile }} lectures/lec-number-theory.typ

lec-probability:
    {{ compile }} lectures/lec-probability.typ

lec-generating-fns:
    {{ compile }} lectures/lec-generating-fns.typ

lec-constructions:
    {{ compile }} lectures/lec-constructions.typ

lec-automata:
    {{ compile }} lectures/lec-automata.typ

lec-context-free:
    {{ compile }} lectures/lec-context-free.typ

lec-turing:
    {{ compile }} lectures/lec-turing.typ

course-intro:
    {{ compile }} lectures/course-intro.typ

lectures: lec-logic lec-sets lec-relations lec-functions lec-cardinals lec-orders lec-graphs lec-boolean lec-circuits lec-codes lec-sat lec-logic-programming lec-matroids lec-combinatorics lec-number-theory lec-probability lec-generating-fns lec-constructions lec-automata lec-context-free lec-turing course-intro

lint:
    cd notes && uv run ../tools/audit.py
