compile := "typst compile --root ."

[private]
@default:
    just --list

book:
    {{ compile }} notes/book.typ

problems:
    {{ compile }} notes/problems.typ

lec-logic:
    {{ compile }} lectures/lec-logic.typ

lec-sets:
    {{ compile }} lectures/lec-sets.typ

lec-relations:
    {{ compile }} lectures/lec-relations.typ

lec-functions:
    {{ compile }} lectures/lec-functions.typ

lec-cardinals:
    {{ compile }} lectures/lec-cardinals.typ

course-intro:
    {{ compile }} lectures/course-intro.typ

lectures: lec-logic lec-sets lec-relations lec-functions lec-cardinals course-intro

lint:
    cd notes && uv run ../tools/audit.py
