[book]
title = "Discrete Mathematics"
description = "Course materials for Discrete Mathematics at ITMO University"
authors = ["Konstantin Chukharev"]
language = "en"
multilingual = false
src = "src"

[build]
build-dir = "dist"

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/Lipen/discrete-math-course"
edit-url-template = "https://github.com/Lipen/discrete-math-course/edit/master/docs/{path}"
site-url = "/discrete-math-course/"

[output.html.search]
enable = true
limit-results = 30
use-boolean-and = true
boost-title = 2
boost-hierarchy = 1
boost-paragraph = 1
expand = true
heading-split-level = 3

[output.html.fold]
enable = true
level = 0
