[book]
title = "Discrete Mathematics"
authors = ["Konstantin Chukharev"]
description = "Course materials for Discrete Mathematics at ITMO University"
language = "en"

[build]
build-dir = "dist"

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/Lipen/discrete-math-course"
edit-url-template = "https://github.com/Lipen/discrete-math-course/edit/master/docs/{path}"
site-url = "/discrete-math-course/"
smart-punctuation = true
mathjax-support = true

# For more options, see:
# https://rust-lang.github.io/mdBook/format/configuration/renderers.html

[output.html.search]
enable = true
use-boolean-and = true

[output.html.fold]
enable = true
level = 0
