[private]
default:
    @just --list

# Build all course documents
all: syllabus topics-s1 topics-s2 mentors program

# Working program (РПД)
program:
    typst compile --root .. program.typ

# Course syllabus
syllabus:
    typst compile --root .. syllabus.typ

# Topics: semester 1
topics-s1:
    typst compile --root .. topics-s1.typ

# Topics: semester 2
topics-s2:
    typst compile --root .. topics-s2.typ

# Mentor handbook
mentors:
    typst compile --root .. mentors.typ
